/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SineWaveClock.h"
#include "SineWave_aliases.h"
#include "SineWave.h"
#include "Song2Trigger_aliases.h"
#include "Song2Trigger.h"
#include "Song1Trigger_aliases.h"
#include "Song1Trigger.h"
#include "SineWaveGen.h"
#include "Song4Trigger_aliases.h"
#include "Song4Trigger.h"
#include "Song3Trigger_aliases.h"
#include "Song3Trigger.h"
#include "LCD_Char_1.h"
#include "VDAC8_1.h"
#include "ADC_Positive_Input_aliases.h"
#include "ADC_Positive_Input.h"
#include "ADC.h"
#include "PGA.h"
#include "SensorValue2_aliases.h"
#include "SensorValue2.h"
#include "SensorValue4_aliases.h"
#include "SensorValue4.h"
#include "Sensor_Interrupt_aliases.h"
#include "Sensor_Interrupt.h"
#include "SensorValue5_aliases.h"
#include "SensorValue5.h"
#include "SensorValue3_aliases.h"
#include "SensorValue3.h"
#include "Sensor5_aliases.h"
#include "Sensor5.h"
#include "Sensor4_aliases.h"
#include "Sensor4.h"
#include "Sensor3_aliases.h"
#include "Sensor3.h"
#include "Sensor2_aliases.h"
#include "Sensor2.h"
#include "SensorScan.h"
#include "SensorValue1_aliases.h"
#include "SensorValue1.h"
#include "Sensor1_aliases.h"
#include "Sensor1.h"
#include "SineWaveGen_Wave1_DMA_dma.h"
#include "SineWaveGen_Wave2_DMA_dma.h"
#include "SineWaveGen_VDAC8.h"
#include "SineWaveGen_BuffAmp.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "SensorScan_Clock_int.h"
#include "SensorScan_Comp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

